<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'GalgameManager.Test' or '$(MSBuildProjectName)' == 'GalgameManager.Server.Test'">
    <!-- Disable Windows App SDK auto initialization for tests -->
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
    <WindowsAppSdkAutoInitialize>false</WindowsAppSdkAutoInitialize>
    <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
    <WindowsAppSdkCompatibilityInitialize>false</WindowsAppSdkCompatibilityInitialize>
  </PropertyGroup>
</Project>
